### ISSUE TITLE
Use the chart.transform() API C3.js offers

### ISSUE THREAD

**Issue by maxklenk** [maxklenk/angular-chart#48]
To add animations and to not require a full rendering of the chart:
http://c3js.org/samples/transform_line.html

**Comment by dilignt** [comment]
Is there an ETA for this functionality?  I'm updating the chart live over websockets but it re-renders completely every time.

**Comment by maxklenk** [comment]
I am working on support for the transform api right now. It will add support to change the type of dimensions without having to render the whole chart again.
Does this help you or do you need support for updating the data itself http://c3js.org/samples/api_flow.html ?

**Comment by dilignt** [comment]
I got my chart to update using load not flow in the watcher
http://c3js.org/samples/data_load.html

I had to change the structure of the data quite a lot to make it match what
c3 expects in load(), and because of my chart groups per column I don't
think it's suitable for a generic watcher.

**Comment by maxklenk** [comment]
Ok, I think to give users the ability to do what they need full access to the functions is required. How do you access the chart and its functions in your solution?

**Comment by dilignt** [comment]
So I changed the `scope.startSmallDatasetWatcher` in the source to achieve what I wanted
```
scope.startSmallDatasetWatcher = function () {
    return scope.$watch('dataset', function (newValue, oldValue) {
      if (!angular.equals(newValue, oldValue)) {

          var cols = [];
          _.each(newValue, function(r) { cols.push(0); });
          _.each(newValue, function(n, i)  {
              var key = Object.keys(n)[0];
              if (newValue[i][key] != oldValue[i][key]) {
                  cols.unshift(key);
                  cols[i+1] = newValue[i][key];
              }
          });

          var obj = {columns:[cols]};
          scope.chart.load(obj);
      }
    }, true);
};
```
* I used the deep equals parameter on` angular equals` to get a match
* I replaced `scope.updateChart` with other code to dynamically load the data
* Because my data has a group for every column, so that each column has it's own legend that can be individually removed, I've got to change the data in the object to what the c3 load function expects
 * initialise each column to 0
 * increment the column that has changed
* then create the columns object to load into the chart

The chart.load API is different from the `dataset` that is being watched and I didn't see a way of doing this generically for all potential dataset permutations, so this code obviously only works with my individual column groupings

I also had to change the tooltip initialisation code that was putting zero group values in the tooltip after the load.

So the final chart looks like this, and each time a result is updated I push the value to the webpage over a websocket and update the `dataset` object and the changed watcher takes over and dynamically updates the chart

![image](https://cloud.githubusercontent.com/assets/5586296/8249789/abd4c598-1665-11e5-9a2f-68189c784efb.png)

**Comment by maxklenk** [comment]
Great solution. I will think about how to allow adding custom functions to handle the load.

**Comment by maxklenk** [comment]
The `transform()` function is now integrated an released. I will add a new issue when working on `flow()` and `load()`.
