### ISSUE TITLE
Question: redraw chart with disabled zoom.

### ISSUE THREAD

**Issue by malykhinvi** [maxklenk/angular-chart#89]
In the 0.3.0 version ```zoom.enabled === true``` is required to redraw the chart.
The point is that I don't want to zoom the chart via mousewheel, but want to change the range via my own widget. 
In 0.2.5 version, I just changed the ```zoom.range``` param and chart was redrawn.

Do you have any suggestions on how to accomplish that? Thanks in advance.

**Comment by maxklenk** [comment]
I see you point, currently angular-chart only applies a zoom if the zoom is enabled. This was made to ensure that the applying of the zoom range is intended. We can drop this check to allow the behaviour you need.

**Comment by malykhinvi** [comment]
> We can drop this check to allow the behaviour you need.

That would be great, thanks!

**Comment by maxklenk** [comment]
I dropped the check, version 0.3.2 should work for you.

**Comment by random-one** [comment]
@maxklenk I think I have a problem with the check you dropped in the above comment.
I have a pie chart that gets redrawn because of this zoom and I receive and error in c3:
```
Uncaught TypeError: Cannot read property 'data_types' of null
    at ChartInternal.c3_chart_internal_fn.isPieType (c3.js:3581)
```
I don't think pie charts are applicable for zoom, so why to redraw the chart once again?
Maybe the problem is somewhere else but this is where I got so far.
@maxklenk  Could you please check this? I also tested c3 only without angular-chart and without angular and could not reproduce the error.
